name: Test

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        go-version: [ "1.25" ]

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum

      - name: Display Go version
        run: go version
      
      - name: Install dependencies
        run: go get .

      - name: Check docstrings
        run: go build ./tstatic.go
